language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
cache:
  directories:
    - $HOME/.m2
before_install:
  - umask 0022
script:
  - cat /etc/hosts
  - df -h
  - umask
  - ulimit -u
  - ulimit -t
  - ulimit -a
  - whoami
  - git --version
