language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
cache:
  directories:
    - $HOME/.m2
before_install:
  - sed -i -e 's~^127.0.1.1\(.*\)~127.0.0.1\1~g' /etc/hosts
script:
  - cat /etc/hosts
